In [1]:
import os
import sys
sys.path.append(os.path.dirname(os.getcwd()))
from query_helper import get_connection, execute_script, import_csv

def start():
    root_dir = os.path.dirname(os.getcwd())
    raw_data_dir = os.path.join(root_dir, "Raw data")

    conn = get_connection()

    if conn:
        execute_script(conn, "create_tables.sql")
        import_csv(conn, os.path.join(raw_data_dir, "patients.csv"), "patients")
        import_csv(conn, os.path.join(raw_data_dir, "visits.csv"), "visits")
        import_csv(conn, os.path.join(raw_data_dir, "billing.csv"), "billing")
        conn.close()

start()

Connection to database successful.
Executed script: create_tables.sql
Imported 5000 rows from /Users/ramsundar/Documents/IITM-Graded-Projects/Capstone/Raw data/patients.csv into patients
Imported 25000 rows from /Users/ramsundar/Documents/IITM-Graded-Projects/Capstone/Raw data/visits.csv into visits
Imported 25000 rows from /Users/ramsundar/Documents/IITM-Graded-Projects/Capstone/Raw data/billing.csv into billing

In [2]:
import sqlite3
import os
import pandas as pd

root_dir = os.path.dirname(os.getcwd())
conn = sqlite3.connect(os.path.join(root_dir, "Database", "hospital.db"))

print("=== Patients ===")
display(pd.read_sql("SELECT * FROM patients LIMIT 5", conn))

print("=== Visits ===")
display(pd.read_sql("SELECT * FROM visits LIMIT 5", conn))

print("=== Billing ===")
display(pd.read_sql("SELECT * FROM billing LIMIT 5", conn))

conn.close()

=== Patients ===

,patient_id,age,gender,city,insurance_provider,chronic_flag,registration_date
0,1,53,M,Hyderabad,SecureLife,0,2025-05-14
1,2,42,M,Pune,HealthPlus,0,2025-11-18
2,3,56,F,Hyderabad,HealthPlus,0,2025-05-11
3,4,72,M,Chennai,HealthPlus,0,2025-12-18
4,5,40,F,Bangalore,CareOne,1,2025-01-23

=== Visits ===

,visit_id,patient_id,visit_date,department,visit_type,length_of_stay_hours,risk_score,doctor_id
0,1,756,2025-10-18,Cardiology,ER,3.48,Low,169
1,2,4102,2025-04-06,Orthopedics,OPD,15.31,High,148
2,3,2964,2025-07-13,ICU,ER,34.36,Low,153
3,4,4496,2025-11-19,Cardiology,ER,37.89,High,119
4,5,1930,2025-03-29,General,ICU,16.78,Medium,118

=== Billing ===

,bill_id,visit_id,billed_amount,approved_amount,claim_status,payment_days,billing_date
0,1,1,23577.37,0.00,Rejected,16.0,2025-06-18
1,2,2,38178.81,38178.81,Paid,18.0,2025-10-09
2,3,3,5038.97,5038.97,Paid,NaN,2025-01-20
3,4,4,22813.34,22813.34,Paid,16.0,2025-12-24
4,5,5,27106.95,27106.95,Paid,14.0,2025-09-23